12-03 21:33 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 117, in register
    return render_to_response('home.html',context_instance=RequestContext(request,user))
UnboundLocalError: local variable 'user' referenced before assignment
12-03 21:34 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 117, in register
    return render_to_response('home.html',context_instance=RequestContext(request,user))
UnboundLocalError: local variable 'user' referenced before assignment
12-03 21:34 root         DEBUG    valid
12-03 21:34 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 85, in register
    logging.debug('valid %s', form.is_valid())
  File "/Library/Python/2.7/site-packages/django/forms/forms.py", line 124, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/Library/Python/2.7/site-packages/django/forms/forms.py", line 115, in _get_errors
    self.full_clean()
  File "/Library/Python/2.7/site-packages/django/forms/forms.py", line 270, in full_clean
    self._clean_fields()
  File "/Library/Python/2.7/site-packages/django/forms/forms.py", line 290, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/Volumes/Data/project/erp/erp/forms.py", line 71, in clean_userName
    userName =self.changed_data['userName']
TypeError: list indices must be integers, not str
12-03 21:51 root         DEBUG    valid
12-03 21:51 django.db.backends DEBUG    (0.004) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 21:51 root         DEBUG    valid True
12-03 21:51 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 89, in register
    password = cd['password']
KeyError: 'password'
12-03 21:53 root         DEBUG    valid
12-03 21:53 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 21:53 root         DEBUG    valid True
12-03 21:53 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 89, in register
    password = cd['password']
KeyError: 'password'
12-03 21:53 root         DEBUG    valid
12-03 21:53 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 21:53 root         DEBUG    valid True
12-03 21:53 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 89, in register
    password = cd['password']
KeyError: 'password'
12-03 22:04 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:04 root         DEBUG    valid True
12-03 22:04 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 88, in register
    password_in = cd['password']
KeyError: 'password'
12-03 22:05 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:05 root         DEBUG    valid True
12-03 22:05 root         DEBUG    cleand data {'userName': u'stmkmk', 'firstName': u'KIM', 'lastName': u'Moon Geun', 'favoriteAnimal': u'cat', 'hobby': u'Program', 'email': u'gramman75@gmail.com'}
12-03 22:05 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 89, in register
    password_in = cd['password']
KeyError: 'password'
12-03 22:17 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:17 root         DEBUG    valid True
12-03 22:17 root         DEBUG    cleand data {'userName': u'stmkmk', 'firstName': u'KIM', 'lastName': u'Moon Geun', 'favoriteAnimal': u'cat', 'hobby': u'Program', 'email': u'gramman75@gmail.com'}
12-03 22:17 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 89, in register
    password_in = cd['password']
KeyError: 'password'
12-03 22:19 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:19 root         DEBUG    valid True
12-03 22:19 root         DEBUG    cleand data {'userName': u'stmkmk', 'firstName': u'KIM', 'confirm': u'12345', 'lastName': u'Moon Geun', 'favoriteAnimal': u'cat', 'hobby': u'Program', 'password': u'12345', 'email': u'gramman75@gmail.com'}
12-03 22:19 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 96, in register
    aggrement = cd['aggrement']
KeyError: 'aggrement'
12-03 22:20 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:20 root         DEBUG    valid True
12-03 22:20 root         DEBUG    cleand data {'userName': u'stmkmk', 'firstName': u'KIM', 'confirm': u'12345', 'lastName': u'Moon Geun', 'aggrement': u'on', 'favoriteAnimal': u'cat', 'hobby': u'Program', 'password': u'12345', 'email': u'gramman75@gmail.com'}
12-03 22:20 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 98, in register
    user = User(username=userName, password = password_in)
  File "<string>", line 4, in __init__
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/state.py", line 200, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/ext/declarative/base.py", line 421, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'username' is an invalid keyword argument for User
12-03 22:22 django.db.backends DEBUG    (0.004) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:22 root         DEBUG    valid True
12-03 22:22 root         DEBUG    cleand data {'userName': u'stmkmk', 'firstName': u'KIM', 'confirm': u'12345', 'lastName': u'Moon Geun', 'aggrement': u'on', 'favoriteAnimal': u'cat', 'hobby': u'Program', 'password': u'12345', 'email': u'gramman75@gmail.com'}
12-03 22:22 django.db.backends DEBUG    (0.000) INSERT INTO `auth_user` (`username`, `first_name`, `last_name`, `email`, `password`, `is_staff`, `is_active`, `is_superuser`, `last_login`, `date_joined`) VALUES ('stmkmk', '', '', '', '12345', 0, 1, 0, '2012-12-03 13:22:35', '2012-12-03 13:22:35'); args=[u'stmkmk', '', '', '', u'12345', False, True, False, u'2012-12-03 13:22:35', u'2012-12-03 13:22:35']
12-03 22:22 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 2 ; args=(2,)
12-03 22:22 django.request ERROR    Internal Server Error: /erp/registerProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 102, in register
    p = user.get_profile()
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 400, in get_profile
    self._state.db).get(user__id__exact=self.id)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 361, in get
    num = len(clone)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 85, in __len__
    self._result_cache = list(self.iterator())
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/Library/Python/2.7/site-packages/MySQL_python-1.2.4b4-py2.7-macosx-10.8-intel.egg/MySQLdb/cursors.py", line 202, in execute
    self.errorhandler(self, exc, value)
  File "/Library/Python/2.7/site-packages/MySQL_python-1.2.4b4-py2.7-macosx-10.8-intel.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1146, "Table 'erp.erp_userprofile' doesn't exist")
12-03 22:22 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 2  LIMIT 21; args=(2,)
12-03 22:22 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` LIMIT 21; args=()
12-03 22:22 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 2  LIMIT 21; args=(2,)
12-03 22:22 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 2  LIMIT 21; args=(2,)
12-03 22:23 django.db.backends DEBUG    (0.001) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmkmk' ; args=(u'stmkmk',)
12-03 22:23 root         DEBUG    valid False
12-03 22:35 django.db.backends DEBUG    (0.005) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmcej' ; args=(u'stmcej',)
12-03 22:35 root         DEBUG    valid True
12-03 22:35 root         DEBUG    cleand data {'userName': u'stmcej', 'firstName': u'Cho', 'confirm': u'12345', 'lastName': u'enju', 'aggrement': u'on', 'favoriteAnimal': u'dog', 'hobby': u'eat', 'password': u'12345', 'email': u'stmcej@lsis.biz'}
12-03 22:35 django.db.backends DEBUG    (0.000) INSERT INTO `auth_user` (`username`, `first_name`, `last_name`, `email`, `password`, `is_staff`, `is_active`, `is_superuser`, `last_login`, `date_joined`) VALUES ('stmcej', '', '', '', '12345', 0, 1, 0, '2012-12-03 13:35:16', '2012-12-03 13:35:16'); args=[u'stmcej', '', '', '', u'12345', False, True, False, u'2012-12-03 13:35:16', u'2012-12-03 13:35:16']
12-03 22:35 django.db.backends DEBUG    (0.000) INSERT INTO `erp_userprofile` (`user_id`, `accepted_eula`, `hobby`, `favorite_animal`) VALUES (5, 0, '', ''); args=[5, False, '', '']
12-03 22:35 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 5 ; args=(5,)
12-03 22:35 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `erp_userprofile` WHERE `erp_userprofile`.`id` = 2  LIMIT 1; args=(2,)
12-03 22:35 django.db.backends DEBUG    (0.000) UPDATE `erp_userprofile` SET `user_id` = 5, `accepted_eula` = 1, `hobby` = 'eat', `favorite_animal` = '' WHERE `erp_userprofile`.`id` = 2 ; args=(5, True, u'eat', u'', 2)
12-03 22:35 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:35:17' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:35:17')
12-03 22:35 django.db.backends DEBUG    (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:35:25' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:35:25')
12-03 22:35 django.db.backends DEBUG    (0.000) SELECT `django_site`.`id`, `django_site`.`domain`, `django_site`.`name` FROM `django_site` WHERE `django_site`.`id` = 1 ; args=(1,)
12-03 22:35 django.db.backends DEBUG    (0.000) SAVEPOINT s4524855296_x1; args=()
12-03 22:35 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  LIMIT 1; args=('ec69855e70d53761b05737ae24ad742f',)
12-03 22:35 django.db.backends DEBUG    (0.000) UPDATE `django_session` SET `session_data` = 'YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', `expire_date` = '2012-12-17 13:35:25' WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f' ; args=('YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', u'2012-12-17 13:35:25', 'ec69855e70d53761b05737ae24ad742f')
12-03 22:35 root         DEBUG    valid True
12-03 22:35 django.db.backends DEBUG    (0.001) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmcej' ; args=(u'stmcej',)
12-03 22:35 django.request ERROR    Internal Server Error: /erp/loginProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 52, in loginProcess
    user = authenticate(username=userName, password=password)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 45, in authenticate
    user = backend.authenticate(**credentials)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/backends.py", line 15, in authenticate
    if user.check_password(password):
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 304, in check_password
    return check_password(raw_password, self.password, setter)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/hashers.py", line 42, in check_password
    hasher = get_hasher(algorithm)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/hashers.py", line 115, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm '12345'. Did you specify it in the PASSWORD_HASHERS setting?
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmsws' ; args=(u'stmsws',)
12-03 22:44 root         DEBUG    valid True
12-03 22:44 root         DEBUG    cleand data {'userName': u'stmsws', 'firstName': u'Shin', 'confirm': u'12345', 'lastName': u'Wonsep', 'aggrement': u'on', 'favoriteAnimal': u'dog', 'hobby': u'game', 'password': u'12345', 'email': u'stmsws@lsis.biz'}
12-03 22:44 django.db.backends DEBUG    (0.000) INSERT INTO `auth_user` (`username`, `first_name`, `last_name`, `email`, `password`, `is_staff`, `is_active`, `is_superuser`, `last_login`, `date_joined`) VALUES ('stmsws', 'Shin', 'Wonsep', '', '12345', 0, 1, 0, '2012-12-03 13:44:47', '2012-12-03 13:44:47'); args=[u'stmsws', u'Shin', u'Wonsep', '', u'12345', False, True, False, u'2012-12-03 13:44:47', u'2012-12-03 13:44:47']
12-03 22:44 django.db.backends DEBUG    (0.000) INSERT INTO `erp_userprofile` (`user_id`, `accepted_eula`, `hobby`, `favorite_animal`) VALUES (7, 0, '', ''); args=[7, False, '', '']
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 7 ; args=(7,)
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `erp_userprofile` WHERE `erp_userprofile`.`id` = 4  LIMIT 1; args=(4,)
12-03 22:44 django.db.backends DEBUG    (0.000) UPDATE `erp_userprofile` SET `user_id` = 7, `accepted_eula` = 1, `hobby` = 'game', `favorite_animal` = '' WHERE `erp_userprofile`.`id` = 4 ; args=(7, True, u'game', u'', 4)
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:44:47' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:44:47')
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:44:50' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:44:50')
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT `django_site`.`id`, `django_site`.`domain`, `django_site`.`name` FROM `django_site` WHERE `django_site`.`id` = 1 ; args=(1,)
12-03 22:44 django.db.backends DEBUG    (0.000) SAVEPOINT s4477345792_x1; args=()
12-03 22:44 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  LIMIT 1; args=('ec69855e70d53761b05737ae24ad742f',)
12-03 22:44 django.db.backends DEBUG    (0.001) UPDATE `django_session` SET `session_data` = 'YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', `expire_date` = '2012-12-17 13:44:50' WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f' ; args=('YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', u'2012-12-17 13:44:50', 'ec69855e70d53761b05737ae24ad742f')
12-03 22:44 root         DEBUG    valid True
12-03 22:44 django.db.backends DEBUG    (0.001) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmsws' ; args=(u'stmsws',)
12-03 22:44 django.request ERROR    Internal Server Error: /erp/loginProcess/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Data/project/erp/erp/views.py", line 52, in loginProcess
    user = authenticate(username=userName, password=password)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 45, in authenticate
    user = backend.authenticate(**credentials)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/backends.py", line 15, in authenticate
    if user.check_password(password):
  File "/Library/Python/2.7/site-packages/django/contrib/auth/models.py", line 304, in check_password
    return check_password(raw_password, self.password, setter)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/hashers.py", line 42, in check_password
    hasher = get_hasher(algorithm)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/hashers.py", line 115, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm '12345'. Did you specify it in the PASSWORD_HASHERS setting?
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmshj' ; args=(u'stmshj',)
12-03 22:46 root         DEBUG    valid True
12-03 22:46 root         DEBUG    cleand data {'userName': u'stmshj', 'firstName': u'Seo', 'confirm': u'12345', 'lastName': u'hyenjin', 'aggrement': u'on', 'favoriteAnimal': u'dog', 'hobby': u'game', 'password': u'12345', 'email': u'stmshj@lsis.biz'}
12-03 22:46 django.db.backends DEBUG    (0.000) INSERT INTO `auth_user` (`username`, `first_name`, `last_name`, `email`, `password`, `is_staff`, `is_active`, `is_superuser`, `last_login`, `date_joined`) VALUES ('stmshj', 'Seo', 'hyenjin', '', 'pbkdf2_sha256$10000$wYetLkPkYfxw$6YNQosDnL1j6iRmEIS4x6wtxcn5uOFeA5D7yPrcyfog=', 0, 1, 0, '2012-12-03 13:46:26', '2012-12-03 13:46:26'); args=[u'stmshj', u'Seo', u'hyenjin', '', 'pbkdf2_sha256$10000$wYetLkPkYfxw$6YNQosDnL1j6iRmEIS4x6wtxcn5uOFeA5D7yPrcyfog=', False, True, False, u'2012-12-03 13:46:26', u'2012-12-03 13:46:26']
12-03 22:46 django.db.backends DEBUG    (0.000) INSERT INTO `erp_userprofile` (`user_id`, `accepted_eula`, `hobby`, `favorite_animal`) VALUES (8, 0, '', ''); args=[8, False, '', '']
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `erp_userprofile`.`id`, `erp_userprofile`.`user_id`, `erp_userprofile`.`accepted_eula`, `erp_userprofile`.`hobby`, `erp_userprofile`.`favorite_animal` FROM `erp_userprofile` WHERE `erp_userprofile`.`user_id` = 8 ; args=(8,)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `erp_userprofile` WHERE `erp_userprofile`.`id` = 5  LIMIT 1; args=(5,)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `erp_userprofile` SET `user_id` = 8, `accepted_eula` = 1, `hobby` = 'game', `favorite_animal` = '' WHERE `erp_userprofile`.`id` = 5 ; args=(8, True, u'game', u'', 5)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:46:26' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:46:26')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:46:29' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:46:29')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_site`.`id`, `django_site`.`domain`, `django_site`.`name` FROM `django_site` WHERE `django_site`.`id` = 1 ; args=(1,)
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  LIMIT 1; args=('ec69855e70d53761b05737ae24ad742f',)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `django_session` SET `session_data` = 'YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', `expire_date` = '2012-12-17 13:46:29' WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f' ; args=('YTBmNjMwMzU3N2JkZmFkNTU5MGY2Y2ZmNjU5OWM5NTJlZTNmZGVhYjqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2VkcQJzLg==\n', u'2012-12-17 13:46:29', 'ec69855e70d53761b05737ae24ad742f')
12-03 22:46 root         DEBUG    valid True
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'stmshj' ; args=(u'stmshj',)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f'  AND `django_session`.`expire_date` > '2012-12-03 13:46:35' ); args=('ec69855e70d53761b05737ae24ad742f', u'2012-12-03 13:46:35')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc'  LIMIT 1; args=('b35485a61bbb818146b81312da5d51cc',)
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('b35485a61bbb818146b81312da5d51cc', 'ZGYxMWMyYTdhZGU1YTQ1ZjY5NmIyM2FkYzQwZTc2NTlhOWUyYTFiNDqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2Vkcy4=\n', '2012-12-17 13:46:35'); args=('b35485a61bbb818146b81312da5d51cc', 'ZGYxMWMyYTdhZGU1YTQ1ZjY5NmIyM2FkYzQwZTc2NTlhOWUyYTFiNDqAAn1xAVUKdGVzdGNvb2tp\nZVUGd29ya2Vkcy4=\n', u'2012-12-17 13:46:35')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE `django_session`.`session_key` = 'ec69855e70d53761b05737ae24ad742f' ; args=('ec69855e70d53761b05737ae24ad742f',)
12-03 22:46 django.db.backends DEBUG    (0.000) DELETE FROM `django_session` WHERE `session_key` IN ('ec69855e70d53761b05737ae24ad742f'); args=(u'ec69855e70d53761b05737ae24ad742f',)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `auth_user` WHERE `auth_user`.`id` = 8  LIMIT 1; args=(8,)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `auth_user` SET `username` = 'stmshj', `first_name` = 'Seo', `last_name` = 'hyenjin', `email` = '', `password` = 'pbkdf2_sha256$10000$wYetLkPkYfxw$6YNQosDnL1j6iRmEIS4x6wtxcn5uOFeA5D7yPrcyfog=', `is_staff` = 0, `is_active` = 1, `is_superuser` = 0, `last_login` = '2012-12-03 13:46:35', `date_joined` = '2012-12-03 13:46:26' WHERE `auth_user`.`id` = 8 ; args=(u'stmshj', u'Seo', u'hyenjin', u'', u'pbkdf2_sha256$10000$wYetLkPkYfxw$6YNQosDnL1j6iRmEIS4x6wtxcn5uOFeA5D7yPrcyfog=', False, True, False, u'2012-12-03 13:46:35', u'2012-12-03 13:46:26', 8)
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc'  LIMIT 1; args=('b35485a61bbb818146b81312da5d51cc',)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `django_session` SET `session_data` = 'ZDY2OTQ0YmM2NjNlM2JhYjIzOWY0ZjJmNzcxM2NlMWY4Mzc5MjEwMDqAAn1xAShVCnRlc3Rjb29r\naWVVBndvcmtlZFUSX2F1dGhfdXNlcl9iYWNrZW5kcQJVKWRqYW5nby5jb250cmliLmF1dGguYmFj\na2VuZHMuTW9kZWxCYWNrZW5kcQNVDV9hdXRoX3VzZXJfaWRxBIoBCHUu\n', `expire_date` = '2012-12-17 13:46:35' WHERE `django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc' ; args=('ZDY2OTQ0YmM2NjNlM2JhYjIzOWY0ZjJmNzcxM2NlMWY4Mzc5MjEwMDqAAn1xAShVCnRlc3Rjb29r\naWVVBndvcmtlZFUSX2F1dGhfdXNlcl9iYWNrZW5kcQJVKWRqYW5nby5jb250cmliLmF1dGguYmFj\na2VuZHMuTW9kZWxCYWNrZW5kcQNVDV9hdXRoX3VzZXJfaWRxBIoBCHUu\n', u'2012-12-17 13:46:35', 'b35485a61bbb818146b81312da5d51cc')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc'  AND `django_session`.`expire_date` > '2012-12-03 13:46:41' ); args=('b35485a61bbb818146b81312da5d51cc', u'2012-12-03 13:46:41')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 8 ; args=(8,)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc'  AND `django_session`.`expire_date` > '2012-12-03 13:46:42' ); args=('b35485a61bbb818146b81312da5d51cc', u'2012-12-03 13:46:42')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `auth_user`.`id`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`password`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`is_superuser`, `auth_user`.`last_login`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 8 ; args=(8,)
12-03 22:46 django.db.backends DEBUG    (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE `django_session`.`session_key` = 'b35485a61bbb818146b81312da5d51cc' ; args=('b35485a61bbb818146b81312da5d51cc',)
12-03 22:46 django.db.backends DEBUG    (0.000) DELETE FROM `django_session` WHERE `session_key` IN ('b35485a61bbb818146b81312da5d51cc'); args=(u'b35485a61bbb818146b81312da5d51cc',)
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989'  LIMIT 1; args=('ce98012c5c8b490db6dfe59f6d903989',)
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('ce98012c5c8b490db6dfe59f6d903989', 'NWIyNGEzNjk3OGVjZWYzN2I3Yzc4OTgwMjY1NjA3YTljOWVjNzIyMjqAAn1xAS4=\n', '2012-12-17 13:46:42'); args=('ce98012c5c8b490db6dfe59f6d903989', 'NWIyNGEzNjk3OGVjZWYzN2I3Yzc4OTgwMjY1NjA3YTljOWVjNzIyMjqAAn1xAS4=\n', u'2012-12-17 13:46:42')
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989'  LIMIT 1; args=('ce98012c5c8b490db6dfe59f6d903989',)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `django_session` SET `session_data` = 'NWIyNGEzNjk3OGVjZWYzN2I3Yzc4OTgwMjY1NjA3YTljOWVjNzIyMjqAAn1xAS4=\n', `expire_date` = '2012-12-17 13:46:42' WHERE `django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989' ; args=('NWIyNGEzNjk3OGVjZWYzN2I3Yzc4OTgwMjY1NjA3YTljOWVjNzIyMjqAAn1xAS4=\n', u'2012-12-17 13:46:42', 'ce98012c5c8b490db6dfe59f6d903989')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989'  AND `django_session`.`expire_date` > '2012-12-03 13:46:47' ); args=('ce98012c5c8b490db6dfe59f6d903989', u'2012-12-03 13:46:47')
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989'  AND `django_session`.`expire_date` > '2012-12-03 13:46:47' ); args=('ce98012c5c8b490db6dfe59f6d903989', u'2012-12-03 13:46:47')
12-03 22:46 django.db.backends DEBUG    (0.000) SAVEPOINT s4550623232_x1; args=()
12-03 22:46 django.db.backends DEBUG    (0.000) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989'  LIMIT 1; args=('ce98012c5c8b490db6dfe59f6d903989',)
12-03 22:46 django.db.backends DEBUG    (0.000) UPDATE `django_session` SET `session_data` = 'Y2QxNjVlOGMxMDFmN2IxNThmNWFjNzY0YTkwODY3YWJiNTIzNmZhNzqAAn1xAVUKdGVzdGNvb2tp\nZXECVQZ3b3JrZWRxA3Mu\n', `expire_date` = '2012-12-17 13:46:47' WHERE `django_session`.`session_key` = 'ce98012c5c8b490db6dfe59f6d903989' ; args=('Y2QxNjVlOGMxMDFmN2IxNThmNWFjNzY0YTkwODY3YWJiNTIzNmZhNzqAAn1xAVUKdGVzdGNvb2tp\nZXECVQZ3b3JrZWRxA3Mu\n', u'2012-12-17 13:46:47', 'ce98012c5c8b490db6dfe59f6d903989')
